### ISSUE TITLE
Tenant selection based on url prefix

### ISSUE THREAD

**Issue by ghost** [django-tenants/django-tenants#183]
hello, I created a middleware to get the tenant from the URL (eg.example.com/tenant1/). But url reversing for admin app is not working. How to fix the issue with url reversing in Django while using different tenant selection option.

**Comment by kosz85** [comment]
Using path prefixes is tricky, you may need to replace django url reverse function with your own replacement. If this is a problem you have. As you just said "not working" which is the worst description of problem ever.

**Comment by tomturner** [comment]
I would make all tenants go to a url such as http://example.com/r/tenant1/ then your middleware wouldn’t Clash with the django admin urls

**Comment by kosz85** [comment]
Yeah, that's true I use `/tnt/<tenant>/`, same reasons.

**Comment by coler-j** [comment]
Anyone care to share their tenant selection middleware from URL prefix?

**Comment by fsladkey** [comment]
I'm currently encountering the same problem, and any advice would be appreciated. I've tried to outline some approaches I've tried to give more context.

I am successfully setting the current tenant in the middleware, but  by setting my admin path with `path("/tnt/<tenant>/admin", admin.site.urls)` my admin breaks with the error "{View name} received an unexpected keyword argument 'tenant'". Of course, I don't care about the `tenant` arg here, since the tenant is already set via the middleware, but I understand why the view is complaining. :)

I thought I might be able to create a tenant specific URLconf on the fly similar to the way we set the public, by setting `request.urlconf = settings.ROOT_URLCONF + [path(f"/tnt/{tenant.schema_name}/admin", admin.site.urls)]` but that doesn't work because `request.urlconf`is the path to the settings rather than an array of `urlpatterns`.

I can just manually create an admin url per tenant, something like
```python
urlpatterns = [
   ...
] + [path(f"/tnt/{tenant.schema_name}/admin", admin.site.urls) for tnt in Tenant.objects.all()]
```

However, the trouble there is that if you add a new tenant, the admin URLs don't exist until the application is restarted. As an experiment, I tried reload the URLconf per request, and while that works I don't think it's a reasonable approach to solving the problem.

I'm pretty new to django in general, so I may be missing an obvious solution here. Anything to point me in the right direction would be appreciated since I'm quite confident it's possible to do this in a reasonable way. Also, thanks for your work on `django-tenants`! It's been working out great so far, only running into trouble now that I'm trying to do something non-standard.

**Comment by lorinkoz** [comment]
There might be a feasible way of doing this mimicing the behavior of Django's `i18n_patterns`. You'd have to extend the `DomainMixin` to include a folder, and do a little bit of dark magic to wrap urlpatterns in a prefix handler like `i18n_patterns` automatically (without asking the user to do so.)

**Comment by lorinkoz** [comment]
@coler-j This could work. Notice that in the example there is some irrelevant logic to `django-tenants`, as I am using statically configured tenants in the mix.

https://github.com/lorinkoz/django-pgschemas/blob/master/django_pgschemas/urlresolvers.py (this just mimics what `i18n_patterns` already does for prepending the current language to every URL and properly reversing it)

https://github.com/lorinkoz/django-pgschemas/blob/master/django_pgschemas/middleware.py (lines 57-65 as of today)

The dark magic is creating the wrapped urlconf module on-the-fly. This is not necessary, you could ask the user to wrap their main urlconf in `tenant_patterns` and provide that as part of the settings.

**Comment by charlierz** [comment]
@fsladkey Did you manage to solve your problem? I am currently having the exact same issue.

**Comment by lorinkoz** [comment]
I can work on a patch for integrating this with `django-tenants`, but I need a design decision from @tomturner about adding a new field to `DomainMixin` so as to control the path part of the url routing.

**Comment by fsladkey** [comment]
Hey @charlierz! We didn't solve this problem the way I was hoping to. We ended up adding a jet dashboard module to set the current tenant in the session and updated the middleware to grab the tenant from session when hitting admin paths. Not ideal but it allowed us to keeping moving with the project and makes the admin usable. The proposed solution by @lorinkoz is interesting but I haven't tried it myself! Would love to update to something like that in the future.

**Comment by tomturner** [comment]
Would love a middleware todo this.

**Comment by lorinkoz** [comment]
@tomturner Are you willing to expand the `Domain` model with a `subfolder` field?

**Comment by tomturner** [comment]
@lorinkoz You don't really need a subfolder field as you can use the domain field in this mode.

**Comment by lorinkoz** [comment]
So we would need at least a new setting for the common domain. I assume the end result would look like:

```python
# settings.py
COMMON_DOMAIN = 'clients.domain.com'
```

Then the urls be like:
clients.domain.com/<domain>/path/to/view/

Is this correct?

**Comment by lorinkoz** [comment]
Please notice that the benefit of having a subfolder field in the domain mixin is that both routing modes can coexist. You can have some tenants available through subdomain while other through subfolder, or both.
