### ISSUE TITLE
Question: Can I use anything but subdomain to determine tenant? 

### ISSUE THREAD

**Issue by epschroeder** [django-tenants/django-tenants#409]
Hello, 

Is it possible to use anything else than subdomain to determine the tenant? 
I like the way django-tenant-schemas allowes a custom header:

https://django-tenant-schemas.readthedocs.io/en/latest/advanced_usage.html?highlight=header#custom-tenant-strategies-custom-middleware-support

Thanks for your reply!
Egbert

**Comment by mcroni** [comment]
that's why a table called `Client` exists in this app

**Comment by epschroeder** [comment]
Can you please explain your answer?

**Comment by mcroni** [comment]
```
tenant = Client(schema_name=s_name, name=company_name, paid_until=arrow.now().shift(days=30).date(), on_trial=True)
tenant.save()

                    # migrate_schemas automatically called, your tenant is ready to be used!
                    # Add one or more domains for the tenant
 logger.info("saved client")
domain = Domain()
domain.domain = f'{s_name}.test.local'  # don't add your port or www here!
   # domain.domain = f'{s_name}.xxxx.com'  # don't add your port or www here!
domain.tenant = tenant
domain.is_primary = True
domain.save()
```

so this an example of the setup i have in my codes . Now, if i want to determine which tenant is currently in connection i do this.

```
from django.db import connection
from whichever_app_holds_your_client_model.models import Client

tenant  = Client.objects.get(schema_name=connection.schema_name)
```
I hope this helps

**Comment by hmamman** [comment]
@mcroni if at all I understood @epschroeder correctly, he meant whether there is any way that the **TenantMainMiddleware** could be customized to identify a tenant using a different strategy rather than the default subdomain strategy? Django-tenant-schemas has a custom way to identify a tenant using HTTP header. Check [Advance section](https://django-tenant-schemas.readthedocs.io/en/latest/advanced_usage.html) of the library documentation. This is a required feature especially when you are using django-tenants on the back-end API as in my case.

I have been working this week towards achieving similar feature.

**Comment by hmamman** [comment]
@epschroeder give this code a try:

`from django_tenants.middleware import TenantMainMiddleware


class CustomTenantMiddleware(TenantMainMiddleware):

    @staticmethod
    def hostname_from_request(request):
        """ Extracts hostname from request. Used for custom requests filtering.
            By default removes the request's port and common prefixes.
        """
        hostname = remove_www(request.get_host().split(':')[0])
        schema = request.META.get('HTTP_SCHEMA')
        if schema:
            return schema + '.' + hostname
        return hostname`
This is assumed you have a custom HTTP header as in [Django Tenant Schemas](https://django-tenant-schemas.readthedocs.io/en/latest/advanced_usage.html)

**Comment by tomturner** [comment]
You can now use sub folders see the example
