### ISSUE TITLE
Programming Errors

### ISSUE THREAD

**Issue by 5starkarma** [django-tenants/django-tenants#431]
I have been using django-tenants for awhile now and keep running across these `ProgrammingError`s when trying to delete tenants. It seems I can never get it to delete tenants or if they do get deleted, it isn't fully deleted; if I try to create another tenant with the same name it will say it already exists.

Here is the recent traceback:

```
ProgrammingError at /admin/companies/company/5/delete/
relation "memos_memo_company" does not exist
LINE 1: ..."memo_id", "memos_memo_company"."company_id" FROM "memos_mem...
```

This happens every single time I try to delete a tenant.

I have edited the `delete_queryset` method of the admin panel:

```
    def delete_queryset(self, request, queryset):
        with schema_context('public'):
            queryset.delete()
```
But that didn't help. It only changed the error to this:

```
ProgrammingError at /admin/companies/company/5/delete/
relation "videos_video_unviewed" does not exist
LINE 1: ...o_id", "videos_video_unviewed"."employee_id" FROM "videos_vi...
```

What is the issue with Django Tenants not seeing columns in the database? Has anyone had this issue? How do I fix it?

**Comment by mcroni** [comment]
```
 def delete_queryset(self, request, queryset):
        with schema_context('public'):
            queryset.delete()
```
your codes are not clear enough, deleting a tenant doesn't guarantee that the schema tied to it also gets dropped . To drop a schema when its associated tenant gets deleted , you need to `auto_drop_schema ` as `True`. Please check the link below. Maybe the error might be due to the fact that the schema still exists
 
[https://github.com/django-tenants/django-tenants/blob/fff6aaa2a3121b70f46148d61f7f1bc1b1e3e31b/django_tenants/models.py#L128](url)

**Comment by 5starkarma** [comment]
Hi! Sorry for not being clear. The Model has auto drop set to 'True' already.
