### ISSUE TITLE
how to collect static file for all schema at once?

### ISSUE THREAD

**Issue by prince-tanapong** [django-tenants/django-tenants#544]
I want to collectstatic file for all schema at once, follow the doc said
```
The command to collect the static files for all tenants is collectstatic_schemas. The optional --schema argument can be used to only collect files for a single tenant.
```

But when I run  `collectstatic_schemas` without `--schema`, it asks me to put schema, it never works with automated deploy

Do you have any suggestions?

**Comment by hanckmann** [comment]
Same issue here.

The issue is surprising, since the documentation states that this should be possible: https://django-tenants.readthedocs.io/en/latest/files.html?highlight=collectstatic_schemas#configuring-the-static-files-storage

	python manage.py collectstatic_schemas

	Enter Tenant Schema ('?' to list schemas): tenant

	You have requested to collect static files at the destination
	location as specified in your settings:

	    /app/.assets/tenant

	This will overwrite existing files!
	Are you sure you want to do this?

	Type 'yes' to continue, or 'no' to cancel: yes

	8 static files copied to '/app/.assets/tenant', 191 unmodified.

This process requires 2 user interactions:

1. entering the tenant name to collect the static files from
2. typing yes to overwrite the existing files

So even if I manage to automatically loop over all my tenants manually, then I still have to type `yes` each time.

Both these are (related) issues.

**Comment by hanckmann** [comment]
I check if I could get this working and send it as a pull request, but it will take some more restructuring than I would be comfortable with. I do not mind helping! Please let me know how I can do that!

**Comment by hanckmann** [comment]
Oke, I only just realised that the `Type 'yes' to continue, or 'no' to cancel:` question can be skipped using the default Django option `--noinput`.

**Comment by tomturner** [comment]
Did you sort the problem out if not please reopen ticket

**Comment by hanckmann** [comment]
I did not manage to sort this problem.
I think we should reopen this ticket.

The first comment describes the issue correctly.

**Comment by rikva** [comment]
For anyone coming across this issue, there is an undocumented `--all-schemas` flag.
