### ISSUE TITLE
Move a schema tenant to another VPS

### ISSUE THREAD

**Issue by anugrahsoft** [django-tenants/django-tenants#880]
Hi,

Imagine we have a SaaS in production with django-tenant, and having thousands of tenants.

some Client(customer) want to have their SaaS solution in their business place(In-Premise, Their own servers). Is it easy to move the tenant schema and some public tables to the new db Server alongside django  and call it a day, or the process is so hard and you advice to not to.

Thank you

**Comment by tomturner** [comment]
It should be possible. I basically move a tenant to my local dev computer when I need to work on it.

**Comment by infosrabah** [comment]
We will be facing this approach a lots, since we still on our development stage, 
Besides of avoiding ForeinKeys from Tenant apps to public (Shared Aps) as much as possible.. what other things should we consider to make the processes of moving tenant from Saas (Online) to Premise(Local) smooth ?

All advices are welcom even non technical.

Tanak you so much

**Comment by tomturner** [comment]
Might be best to ask on stack overflow
